package bg.sofia.uni.fmi.mjt.game.recommender.util;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.stream.Collectors;

public class GamesStreamInitializer {
    private static InputStream gameStream = null;

    private static final String[] games = {
            "The Legend of Zelda: Ocarina of Time,Nintendo 64,23-Nov-1998,As a young boy Link is tricked by Ganondorf the King of the Gerudo Thieves. The evil human uses Link to gain access to the Sacred Realm where he places his tainted hands on Triforce and transforms the beautiful Hyrulean landscape into a barren wasteland. Link is determined to fix the problems he helped to create so with the help of Rauru he travels through time gathering the powers of the Seven Sages.,99,9.1",
            "Tony Hawk's Pro Skater 2,PlayStation,20-Sep-2000,As most major publishers' development efforts shift to any number of next-generation platforms Tony Hawk 2 will likely stand as one of the last truly fantastic games to be released on the PlayStation.,98,7.4",
            "Grand Theft Auto IV,PlayStation 3,29-Apr-2008,[Metacritic's 2008 PS3 Game of the Year; Also known as GTA IV] What does the American Dream mean today? For Niko Belic fresh off the boat from Europe. It's the hope he can escape his past. For his cousin Roman it is the vision that together they can find fortune in Liberty City gateway to the land of opportunity. As they slip into debt and are dragged into a criminal underworld by a series of shysters thieves and sociopaths they discover that the reality is very different from the dream in a city that worships money and status and is heaven for those who have them an a living nightmare for those who don't. [Rockstar Games],98,7.7",
            "SoulCalibur,Dreamcast,08-Sep-1999,This is a tale of souls and swords transcending the world and all its history told for all eternity... The greatest weapons-based fighter returns this time on Sega Dreamcast. Soul Calibur unleashes incredible graphics fantastic fighters and combos so amazing they'll make your head spin!,98,8.4",
            "Grand Theft Auto IV,Xbox 360,29-Apr-2008,[Metacritic's 2008 Xbox 360 Game of the Year; Also known as GTA IV] What does the American Dream mean today? For Niko Belic fresh off the boat from Europe. It's the hope he can escape his past. For his cousin Roman it is the vision that together they can find fortune in Liberty City gateway to the land of opportunity. As they slip into debt and are dragged into a criminal underworld by a series of shysters thieves and sociopaths they discover that the reality is very different from the dream in a city that worships money and status and is heaven for those who have them an a living nightmare for those who don't. [Rockstar Games],98,7.9",
            "Super Mario Galaxy,Wii,12-Nov-2007,[Metacritic's 2007 Wii Game of the Year] The ultimate Nintendo hero is taking the ultimate step ... out into space. Join Mario as he ushers in a new era of video games defying gravity across all the planets in the galaxy. When some creature escapes into space with Princess Peach Mario gives chase exploring bizarre planets all across the galaxy. Mario Peach and enemies new and old are here. Players run jump and battle enemies as they explore all the planets in the galaxy. Since this game makes full use of all the features of the Wii Remote players have to do all kinds of things to succeed: pressing buttons swinging the Wii Remote and the Nunchuk and even pointing at and dragging things with the pointer. Since he's in space Mario can perform mind-bending jumps unlike anything he's done before. He'll also have a wealth of new moves that are all based around tilting pointing and shaking the Wii Remote. Shake tilt and point! Mario takes advantage of all the unique aspects of the Wii Remote and Nunchuk controller unleashing new moves as players shake the controller and even point at and drag items with the pointer. [Nintendo],97,9.1",
            "Super Mario Galaxy 2,Wii,23-May-2010,Super Mario Galaxy 2 the sequel to the galaxy-hopping original game includes the gravity-defying physics-based exploration from the first game but is loaded with entirely new galaxies and features to challenge players. On some stages Mario can pair up with his dinosaur buddy Yoshi and use his tongue to grab items and spit them back at enemies. Players can also have fun with new items such as a drill that lets our hero tunnel through solid rock. [Nintendo],97,9.1",
            "Red Dead Redemption 2,Xbox One,26-Oct-2018,Developed by the creators of Grand Theft Auto V and Red Dead Redemption Red Dead Redemption 2 is an epic tale of life in Americaâ€™s unforgiving heartland. The gameâ€™s vast and atmospheric world also provides the foundation for a brand new online multiplayer experience. America 1899. The end of the Wild West era has begun. After a robbery goes badly wrong in the western town of Blackwater Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels the gang has to rob steal and fight their way across the rugged heartland of America in order to survive. As deepening internal fissures threaten to tear the gang apart Arthur must make a choice between his own ideals and loyalty to the gang that raised him. [Rockstar],97,8",
            "Grand Theft Auto V,Xbox One,18-Nov-2014,Grand Theft Auto 5 melds storytelling and gameplay in unique ways as players repeatedly jump in and out of the lives of the game's three protagonists playing all sides of the game's interwoven story.,97,7.9",
            "Grand Theft Auto V,PlayStation 3,17-Sep-2013,Los Santos is a vast sun-soaked metropolis full of self-help gurus starlets and once-important formerly-known-as celebrities. The city was once the envy of the Western world but is now struggling to stay afloat in an era of economic uncertainty and reality TV. Amidst the chaos three unique criminals plot their own chances of survival and success: Franklin a former street gangster in search of real opportunities and serious cheddar; Michael a professional ex-con whose retirement is a lot less rosy than he hoped it would be; and Trevor a violent maniac driven by the chance of a cheap high and the next big score. Quickly running out of options the crew risks it all in a sequence of daring and dangerous heists that could set them up for life.,97,8.3",
            "Disco Elysium: The Final Cut,PC,30-Mar-2021,Disco Elysium - The Final Cut is the definitive edition of the smash-hit RPG. Pursue your political dreams in new quests meet and question more of the city's locals and explore a whole extra area. Full voice-acting controller support and expanded language options also included. Get even more out of this award-winning open world. You're a detective with a unique skill system at your disposal and a whole city block to carve your path across. Interrogate unforgettable characters crack murders or take bribes. Become a hero or an absolute disaster of a human being.,97,8.3",
            "Grand Theft Auto V,Xbox 360,17-Sep-2013,Los Santos is a sprawling sun-soaked metropolis full of self-help gurus starlets and once-important stars. The city was once the envy of the Western world but is now struggling to stay relevant in an era of economic uncertainty and reality TV. Amidst the chaos three very different criminals chart their own chances of survival and success: Franklin a former street gangster now looking for real opportunities and fat stacks of cash; Michael a professional ex-con whose retirement is significantly less rosy than he hoped it would be; and Trevor a violent maniac driven by the chance of a cheap high and the next big score. Rapidly running out of options the crew risks everything in a series of bolt and dangerous heists that could set them up for the long haul.,97,8.3",
            "Tony Hawk's Pro Skater 2,Dreamcast,06-Nov-2000,Hawk's back - with new technology new pros and new tricks! THPS2 the legend rides on! Skate as legendary Tony Hawk or any one of 12 other pro skaters. Create your own custom skaters. Multiple play modes including 1-Player Career and Free Skate modes as well as 2-player modes such as Trick Attack Graffiti Tag and Horse. Build your own custom skate parks with the real-time 3D park editor.,97,6.2",
            "The Legend of Zelda: Breath of the Wild,Switch,03-Mar-2017,Forget everything you know about The Legend of Zelda games. Step into a world of discovery exploration and adventure in The Legend of Zelda: Breath of the Wild a boundary-breaking new game in the acclaimed series. Travel across fields through forests and to mountain peaks as you discover what has become of the ruined kingdom of Hyrule in this open-air adventure. Explore the wilds of Hyrule any way you like - Climb up towers and mountain peaks in search of new destinations then set your own path to get there and plunge into the wilderness. Along the way you'll battle towering enemies hunt wild beasts and gather ingredients for the food and elixirs you'll need to sustain you on your journey. More than 100 Shrines of Trials to discover and explore - Shrines dot the landscape waiting to be discovered in any order you want. Search for them in various ways and solve a variety of puzzles inside. Work your way through the traps and devices inside to earn special items and other rewards that will help you on your adventure. * Be prepared and properly equipped - With an entire world waiting to be explored you'll need a variety of outfits and gear to reach every corner. You may need to bundle up with warmer clothes or change into something better suited to the desert heat. Some clothing even has special effects that for example can make you faster and stealthier. * Battling enemies requires strategy - The world is inhabited with enemies of all shapes and sizes. Each one has its own attack method and weaponry so you must think quickly and develop the right strategies to defeat them. * amiibo compatibility - Tap the Wolf Link amiibo (sold separately) to make Wolf Link appear in game. Wolf Link will attack enemies on his own and help you find items you're searching for.,97,8.7",
            "Tony Hawk's Pro Skater 3,PlayStation 2,28-Oct-2001,Challenge up to four friends in online competitions over a LAN or the Internet. Take them on in both Trick Attack and Graffiti modes. [Activision],97,7.5",
            "Perfect Dark,Nintendo 64,22-May-2000,Step into the Dark... As Carrington Institute's most promising new Agent Joanna Dark must uncover the truth behind the dataDyne Corporation's recent technological breakthroughs - breakthroughs which could have serious consequences for mankind.,97,8.8",
            "Red Dead Redemption 2,PlayStation 4,26-Oct-2018,Developed by the creators of Grand Theft Auto V and Red Dead Redemption Red Dead Redemption 2 is an epic tale of life in Americaâ€™s unforgiving heartland. The gameâ€™s vast and atmospheric world also provides the foundation for a brand new online multiplayer experience. America 1899. The end of the Wild West era has begun. After a robbery goes badly wrong in the western town of Blackwater Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels the gang has to rob steal and fight their way across the rugged heartland of America in order to survive. As deepening internal fissures threaten to tear the gang apart Arthur must make a choice between his own ideals and loyalty to the gang that raised him. [Rockstar],97,8.5",
            "Grand Theft Auto V,PlayStation 4,18-Nov-2014,The sprawling sun-soaked metropolis of Los Santos is chock full of self-help coaches starlets and C-List celebrities once on top of the media world now struggling to stay relevant in time of economic malaise and lowest-common-denominator reality TV. Amidst this madness three unique criminals plan their own chances of survival and success: Franklin a street-level hustler in search of opportunities for serious money; Michael an ex-con whose retirement is a less rosy than he hoped it would be; and Trevor a violent dude driven by the chance for a quick high and the next big score. Nearly out of options the crew risks it all in a series of daring and dangerous heists that could set them up for life - one way or the other.,97,8.4",
            "Metroid Prime,GameCube,17-Nov-2002,Samus returns in a new mission to unravel the mystery behind the ruined walls scattered across Tallon IV. In Metroid Prime you'll play the role of this bounty hunter and view the world through her visor which displays information ranging from current energy levels to ammunition. Equipped with a Power Beam and Gravity Suit you must shoot locked switches solve puzzles and eliminate enemies. It's up to you to explore the world and recover more power-ups and weapons which gradually open more gameplay areas.,97,8.6"
    };


    public static InputStream getGameStream() {
        return new ByteArrayInputStream(
                Arrays.stream(games)
                        .collect(Collectors.joining(System.lineSeparator()))
                        .getBytes(StandardCharsets.UTF_8));
    }
}
